In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

# Assignment 1

In [7]:
n=10
r=5
p=100

A= p * pow(1+(r/100), n)

print(A)

print(type(p))
print(type(r))
print(type(n))
print(type(A))

162.8894626777442
<class 'int'>
<class 'int'>
<class 'int'>
<class 'float'>


# Assignment 2 - Error

In [91]:
import numpy as np
my_list1=[2,7,3,5,4,6]
print(my_list1)
my_arr1 = numpy.array(my_list1,dtype=int)
print(my_arr1)

[2, 7, 3, 5, 4, 6]


NameError: name 'numpy' is not defined

# Assignment3

In [11]:
string1 = 'Machine Learning'
string2=string1.strip('Machine')
print(string2[:-3])

 Learn


# Assignment 4 

In [14]:
l1=[]
for i in range(15,25,4):
    l1.append(i)

print(l1)
print(l1.index(19))

[15, 19, 23]
1


# Assignment 5- Num1 = num2

In [15]:
num1 = 5 ** 4
num2 = pow(5,4)
print(num1,num2)

625 625


# Assignment 6

In [22]:
l1=['Coffee','Tea']
l2=['Hot','Ice']
for i in l1:
    print(i)
    for j in l2:
        print('*',j)


Coffee
* Hot
* Ice
Tea
* Hot
* Ice


 # Assignment 7

In [82]:

a=int(input("Enter the side1 of the triangle:"))
b=int(input("Enter the side2 of the triangle:"))
c=int(input("Enter the side3 of the triangle:"))

if (a*a + b*b == c*c):
    print(a,",",b,",",c,"is a pythogeras triangle")
else:
    print(a,",",b,",",c,"is not a pythogeras triangle")

Enter the side1 of the triangle:1
Enter the side2 of the triangle:1
Enter the side3 of the triangle:1
1 , 1 , 1 is not a pythogeras triangle


# Assignment 8

In [39]:
l1=[]
print("Input the list of integers. Enter 0 to end:")
while(1):
    a=int(input("enter num:"))
    if a==0:
        break
    l1.append(a)
print(l1)

large=max(l1)
small=min(l1)
print("Largest:" ,large)
print("Smallest:",small)



Input the list of integers. Enter 0 to end:
enter num:1
enter num:2
enter num:3
enter num:4
enter num:67
enter num:0
[1, 2, 3, 4, 67]
Largest: 67
Smallest: 1


In [45]:
import statistics as st
l2=[]
print("Input the float of integers. Enter 0 to end:")
while(1):
    a=float(input("enter num:"))
    if a==0:
        break
    l2.append(a)
print(l2)

stdval=st.pstdev(l2)
print("Standard Deviation:",stdval)


Input the float of integers. Enter 0 to end:
enter num:2.34
enter num:45.23
enter num:23.34
enter num:9.34
enter num:0.0
[2.34, 45.23, 23.34, 9.34]
Standard Deviation: 16.379896786915356


# Assignment 9

In [80]:
from itertools import permutations
import string
  
s=input("Enter the string")
p = permutations(s)
# Create a dictionary
d = []
for i in list(p):
  
    # Print only if not in dictionary
    if (i not in d):
        d.append(i)
        #print(''.join(i))
        
print(len(d))

Enter the stringhelo


TypeError: object of type 'itertools.permutations' has no len()

In [77]:
s=input("Enter the string")
totlen=len(s)
d1={}
for i in range(0,totlen):
    count=1
    for j in range(i+1,totlen):
        if (s[i] == s[j] and s[i] != ' ' and s[i] !='0'):
            count =count + 1
            s=s[:j] +'0' + s[j+1:]
    if(count>1):
        d2={s[i]:count}
        d1.update(d2)
print(d1)

den =1
for i in list(d1.values()):
    den = den * math.factorial(i)

combo = math.factorial(totlen)/ den
print("The different combinations are:",combo)





Enter the stringenduringly
{'n': 2}
The different combinations are: 1814400.0


# Assignment 10


In [77]:

M=int(input("Enter the no of men:"))
W=int(input("Enter the no of women:"))

M1 =int(input("Enter the number of men to select"))
W1 =int(input("Enter the number of men to select"))     

M_combo = math.factorial(M)/(math.factorial(M1) * math.factorial(M-M1))
W_combo = math.factorial(W)/(math.factorial(W1) * math.factorial(W-W1))

tot = M_combo * W_combo * M1 * W1

print("The combinations possible are:",tot)



Enter the no of men:12
Enter the no of women:12
Enter the number of men to select6
Enter the number of men to select6
The combinations possible are: 30735936.0


# Assignment 11

In [ ]:
E1- Event of choosing an answer right
E2- Event of knowing the answer
A- event of answering correct

p(E1) = 1/4 , P(E2) = 1/3

P(A/E2) = probability of answering correct when I know the answer  = 1
P(A/E1) = probability of answering it correct  = 1/4

p(A) - probability of answering correct = p(A/E1) * P(E1) + p(A/E2) * P(E2)
                                        = 1/4*1/4 + 1* 1/3 = 

p(E2/A) = p(A/E2) * P(E2)  / p(A)

        = 1 * 1/3 /  48/19
    
        = 12/19
        

# Assignment 12


In [84]:
df_tips= pd.read_csv(r"C:\Users\Priyadarshini\Downloads\Python datasets\CCE-IIT-Madras-Python-for-Data-Science-Assignment\tips.csv")

In [100]:
maxBill=df_tips['TotalBill'].max()
print("MaxBill",maxBill)
desc=df_tips['TotalBill'].describe()
desc75=desc['75%']
print("75%",desc75)
range=df_tips['TotalBill'].max() -df_tips['TotalBill'].min()
print("Range",range)

MaxBill 48.27
75% 23.964999999999996
Range 45.2



# Assignment 14
    

In [88]:
import statistics as st
X = [58,59,63,60,60,63,60,57,58,59]

print(X)
st.pstdev(X)
st.variance(X)

[58, 59, 63, 60, 60, 63, 60, 57, 58, 59]


4.011111111111111

# Assignment 15

In [ ]:
MEdian is 25
Outliers - anything below 5 and above 75.

rough values from image


# Assignment 16

In [105]:
country={'India':'Delhi','China':'Beijing','Japan':'Tokyo','Qatar':'Doha','France':'Marseilles'}

key1=input("Enter the country name for replacement")
key1=key1.lower().strip(' ')
value1=input("Enter the new name for replacement")
for k,v in country.items():
    if k.lower().strip(' ')  == key1:
        country[k] = value1
print(country)

Enter the country name for replacementfrance
Enter the new name for replacementParis
{'India': 'Delhi', 'China': 'Beijing', 'Japan': 'Tokyo', 'Qatar': 'Doha', 'France': 'Paris'}


# Assignment 17 - ans d- tuple_1[3] = 45

In [109]:
tuple_1 = (1,5,6,7,8) 
tuple_2 = (8,9,4)

In [110]:
sum(tuple_1)

27

In [111]:
len(tuple_2)

3

In [112]:
tuple_1+tuple_2

(1, 5, 6, 7, 8, 8, 9, 4)

In [113]:
tuple_1[3] = 45

TypeError: 'tuple' object does not support item assignment

# Assignment 18 - Ans 6

In [1]:
S={1,2,3,4,4,4,5,6}
S

{1, 2, 3, 4, 5, 6}

# Assignment 19

Create an array with whole numbers values from 0 to 10 and find what is the command 
to extract the elements in the following sequence -
array ([7,4,1])

In [38]:
a1=np.arange(0,10)
a1
newarr=a1[np.array([-3,4,1])]
print(newarr)
print(a1[-3:0:-3])

[7 4 1]
[7 4 1]


# Assignment 20
Create a 2-dimensional array with 3 rows and 3 columns containing random numbers 
from 1 to 9. Find the difference between the maximum element across the columns and the 
minimum element across the rows.

In [56]:
a1=np.random.rand(1,9).reshape([3,3])
print(a1)
ans=a1.max()-a1.min()
print("Difference is :",ans)

[[0.64177348 0.65475036 0.71192187]
 [0.05386796 0.83637759 0.21793102]
 [0.72992044 0.36245641 0.44477875]]
Difference is : 0.7825096250914471


# Assignment 21
Consider the following data to answer the question below
What is the command to convert the above dictionary into a dataframe named
‘df_state’?

In [103]:
state_data={'State':['Goa','Goa','Goa','Gujarat','Gujarat','Gujarat'], 
            'Year':['2010','2011','2012','2013','2014','2015'],
            'pop':[2.5,2.7,4.6,3.4,3.9,4.2]
           }
df_state=pd.DataFrame(state_data)
df_state

State  Year  pop
0      Goa  2010  2.5
1      Goa  2011  2.7
2      Goa  2012  4.6
3  Gujarat  2013  3.4
4  Gujarat  2014  3.9
5  Gujarat  2015  4.2

# Assignment 22

 List 3 commands to display the columns of the above dataframe df_state.

In [104]:
df_state.columns

Index(['State', 'Year', 'pop'], dtype='object')

# Assignment 24

In [120]:

df_col=df_tips[["Time", "TotalBill", "Tips"]]
print(list(df_col))
l1=df_tips.columns
l2=[]
for i in l1:
    if i.startswith('T'):
        l2.append(i)
print(l2)

['Time', 'TotalBill', 'Tips']
['TotalBill', 'Tips', 'Time']


# Assignment 25

In [153]:
df_tips1=pd.read_excel(r"C:\Users\Priyadarshini\Downloads\Python datasets\CCE-IIT-Madras-Python-for-Data-Science-Assignment\tips11.xlsx")

In [ ]:
df_tips1

In [159]:
df_tips= pd.read_csv(r"C:\Users\Priyadarshini\Downloads\Python datasets\CCE-IIT-Madras-Python-for-Data-Science-Assignment\tips.csv")

In [160]:
df_tips

SINO  TotalBill  Tips Smoker  Day    Time  Size  Gender
0      1      16.99  1.01     No  Sun  Dinner   2.0  Female
1      2      10.34  1.66     No  Sun  Dinner   3.0    Male
2      3      21.01  3.50     No  Sun  Dinner   3.0    Male
3      4      23.68  3.31     No  Sun  Dinner   2.0    Male
4      5      24.59  3.61     No  Sun  Dinner   4.0  Female
..   ...        ...   ...    ...  ...     ...   ...     ...
95    96      40.17  4.73    Yes  Fri  Dinner   4.0    Male
96    97      27.28  4.00    Yes  Fri  Dinner   2.0    Male
97    98      12.03  1.50    Yes  Fri  Dinner   2.0    Male
98    99      21.01  3.00    Yes  Fri  Dinner   2.0    Male
99   100      25.10   NaN     No  NaN   Lunch   2.0     NaN

[100 rows x 8 columns]

In [156]:
pd.merge(df_tips,df_tips1)

SINO  TotalBill  Tips Smoker  Day    Time  Size  Gender
0      1      16.99  1.01     No  Sun  Dinner   2.0  Female
1      2      10.34  1.66     No  Sun  Dinner   3.0    Male
2      3      21.01  3.50     No  Sun  Dinner   3.0    Male
3      4      23.68  3.31     No  Sun  Dinner   2.0    Male
4      5      24.59  3.61     No  Sun  Dinner   4.0  Female
..   ...        ...   ...    ...  ...     ...   ...     ...
95    96      40.17  4.73    Yes  Fri  Dinner   4.0    Male
96    97      27.28  4.00    Yes  Fri  Dinner   2.0    Male
97    98      12.03  1.50    Yes  Fri  Dinner   2.0    Male
98    99      21.01  3.00    Yes  Fri  Dinner   2.0    Male
99   100      25.10   NaN     No  NaN   Lunch   2.0     NaN

[100 rows x 8 columns]

In [157]:
Data2 = df_tips1.copy()

In [172]:
data=df_tips.groupby(by='Day').sum()['TotalBill']

In [173]:
data

Day
Fri     196.77
Sat     697.43
Sun     632.91
Thur    254.65
Name: TotalBill, dtype: float64

# Assignment 31
Match the terms in Group A with the relevant terms in GroupB
 Group A                             Group B
 K means                             k is no. of clusters
 clustering                          unsupervised learning algorithm     
 knn                                 k is no. of neighbors
 logistic regression                 logit function


# Assignment 32

Each centroid in K- means algorithm defines one  cluster

# assignment 33

 The method / metric which is NOT useful to determine the optimal number of clustersin 
unsupervised clustering algorithms is scatter plot

# Assignment 34

In the K-means algorithm, what is the most commonly used distance metric to calculate 
distance between centroid of each cluster and data points  Euclidean

In [ ]:
# Assignment 35

Which of the following statements is not correct about k-means
K-Means clustering is NOT influenced by initial centroids which are called 
cluster seed

In [ ]:
# Assignmen 25-30

In [2]:
df_stock1=pd.read_csv(r"C:\Users\Priyadarshini\Downloads\Python datasets\CCE-IIT-Madras-Python-for-Data-Science-Assignment\Stock_File_1.csv")

df_stock1.head()

In [4]:
# Assignment 26 30

In [6]:
df_cem=pd.read_csv(r"C:\Users\Priyadarshini\Downloads\Python datasets\CCE-IIT-Madras-Python-for-Data-Science-Assignment\Concrete Compressive Strength.csv")

In [7]:
df_cem.head()

Cement (component 1)(kg in a m^3 mixture)  \
0                                      540.0   
1                                      540.0   
2                                      332.5   
3                                      332.5   
4                                      198.6   

   Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
0                                                0.0       
1                                                0.0       
2                                              142.5       
3                                              142.5       
4                                              132.4       

   Fly Ash (component 3)(kg in a m^3 mixture)  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   

   Water  (component 4)(kg in a m^3 mixture)  \
0                                      162.0   
1                                      162.0   
2                                      228.0   
3                                      228.0   
4                                      192.0   

   Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                                2.5     
1                                                2.5     
2                                                0.0     
3                                                0.0     
4                                                0.0     

   Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
0                                             1040.0      
1                                             1055.0      
2                                              932.0      
3                                              932.0      
4                                              978.4      

   Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
0                                              676.0         28   
1                                              676.0         28   
2                                              594.0        270   
3                                              594.0        365   
4                                              825.5        360   

   Concrete compressive strength(MPa, megapascals)   
0                                         79.986111  
1                                         61.887366  
2                                         40.269535  
3                                         41.052780  
4                                         44.296075

In [14]:
df_cem.columns=['Comp1_cem','Comp2_Blast','Comp3_Ash','Comp4_water','Comp5_plasticizer','Comp6_Coarse','Comp7_Agg','Age','CCS']

In [15]:
df_cem.head()

Comp1_cem  Comp2_Blast  Comp3_Ash  Comp4_water  Comp5_plasticizer  \
0      540.0          0.0        0.0        162.0                2.5   
1      540.0          0.0        0.0        162.0                2.5   
2      332.5        142.5        0.0        228.0                0.0   
3      332.5        142.5        0.0        228.0                0.0   
4      198.6        132.4        0.0        192.0                0.0   

   Comp6_Coarse  Comp7_Agg  Age        CCS  
0        1040.0      676.0   28  79.986111  
1        1055.0      676.0   28  61.887366  
2         932.0      594.0  270  40.269535  
3         932.0      594.0  365  41.052780  
4         978.4      825.5  360  44.296075

In [9]:
#The total number of missing values within the dataset.  - No missing values
df_cem.isna().sum()

Cement (component 1)(kg in a m^3 mixture)                0
Blast Furnace Slag (component 2)(kg in a m^3 mixture)    0
Fly Ash (component 3)(kg in a m^3 mixture)               0
Water  (component 4)(kg in a m^3 mixture)                0
Superplasticizer (component 5)(kg in a m^3 mixture)      0
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     0
Fine Aggregate (component 7)(kg in a m^3 mixture)        0
Age (day)                                                0
Concrete compressive strength(MPa, megapascals)          0
dtype: int64

In [10]:
# Which column / feature requires correction in the type of value they hold
df_cem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column                                                 Non-Null Count  Dtype  
---  ------                                                 --------------  -----  
 0   Cement (component 1)(kg in a m^3 mixture)              1030 non-null   float64
 1   Blast Furnace Slag (component 2)(kg in a m^3 mixture)  1030 non-null   float64
 2   Fly Ash (component 3)(kg in a m^3 mixture)             1030 non-null   float64
 3   Water  (component 4)(kg in a m^3 mixture)              1030 non-null   float64
 4   Superplasticizer (component 5)(kg in a m^3 mixture)    1030 non-null   float64
 5   Coarse Aggregate  (component 6)(kg in a m^3 mixture)   1030 non-null   float64
 6   Fine Aggregate (component 7)(kg in a m^3 mixture)      1030 non-null   float64
 7   Age (day)                                              1030 non-null   int64  
 8   Concrete compressive strength(MPa, megapascals)  

In [16]:
# After imputation of nulls with mean what is the average value of thecompressive strength in concrete?
df_cem['CCS'].mean()

35.81783582611362

In [30]:
# The feature that has a moderately strong relationship with compressive strength in concrete is - Comp1_cem
df_cem.corr()

Comp1_cem  Comp2_Blast  Comp3_Ash  Comp4_water  \
Comp1_cem           1.000000    -0.275193  -0.397475    -0.081544   
Comp2_Blast        -0.275193     1.000000  -0.323569     0.107286   
Comp3_Ash          -0.397475    -0.323569   1.000000    -0.257044   
Comp4_water        -0.081544     0.107286  -0.257044     1.000000   
Comp5_plasticizer   0.092771     0.043376   0.377340    -0.657464   
Comp6_Coarse       -0.109356    -0.283998  -0.009977    -0.182312   
Comp7_Agg          -0.222720    -0.281593   0.079076    -0.450635   
Age                 0.081947    -0.044246  -0.154370     0.277604   
CCS                 0.497833     0.134824  -0.105753    -0.289613   

                   Comp5_plasticizer  Comp6_Coarse  Comp7_Agg       Age  \
Comp1_cem                   0.092771     -0.109356  -0.222720  0.081947   
Comp2_Blast                 0.043376     -0.283998  -0.281593 -0.044246   
Comp3_Ash                   0.377340     -0.009977   0.079076 -0.154370   
Comp4_water                -0.657464     -0.182312  -0.450635  0.277604   
Comp5_plasticizer           1.000000     -0.266303   0.222501 -0.192717   
Comp6_Coarse               -0.266303      1.000000  -0.178506 -0.003016   
Comp7_Agg                   0.222501     -0.178506   1.000000 -0.156094   
Age                        -0.192717     -0.003016  -0.156094  1.000000   
CCS                         0.366102     -0.164928  -0.167249  0.328877   

                        CCS  
Comp1_cem          0.497833  
Comp2_Blast        0.134824  
Comp3_Ash         -0.105753  
Comp4_water       -0.289613  
Comp5_plasticizer  0.366102  
Comp6_Coarse      -0.164928  
Comp7_Agg         -0.167249  
Age                0.328877  
CCS                1.000000

In [71]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_cem.iloc[:,:-1])

In [72]:
df_cem1=pd.DataFrame(scaled_data,columns=['Comp1_cem','Comp2_Blast','Comp3_Ash','Comp4_water','Comp5_plasticizer','Comp6_Coarse','Comp7_Agg','Age'])

In [73]:
df_cem1

Comp1_cem  Comp2_Blast  Comp3_Ash  Comp4_water  Comp5_plasticizer  \
0      2.477918    -0.856886  -0.847132    -0.916663          -0.620225   
1      2.477918    -0.856886  -0.847132    -0.916663          -0.620225   
2      0.491443     0.795533  -0.847132     2.175367          -1.038944   
3      0.491443     0.795533  -0.847132     2.175367          -1.038944   
4     -0.790432     0.678414  -0.847132     0.488805          -1.038944   
...         ...          ...        ...          ...                ...   
1025  -0.045623     0.488241   0.564569    -0.092122           0.451695   
1026   0.392837    -0.856886   0.960095     0.676201           0.702927   
1027  -1.270057     0.759585   0.850661     0.521599          -0.017270   
1028  -1.168580     1.308072  -0.847132    -0.279518           0.853666   
1029  -0.194010     0.308504   0.376967     0.891706           0.401449   

      Comp6_Coarse  Comp7_Agg       Age  
0         0.863160  -1.217658 -0.279733  
1         1.056170  -1.217658 -0.279733  
2        -0.526514  -2.240913  3.553066  
3        -0.526514  -2.240913  5.057677  
4         0.070531   0.647908  4.978487  
...            ...        ...       ...  
1025     -1.323003  -0.065874 -0.279733  
1026     -1.994679   0.496916 -0.279733  
1027     -1.036061   0.080127 -0.279733  
1028      0.214646   0.191188 -0.279733  
1029     -1.395060  -0.150729 -0.279733  

[1030 rows x 8 columns]

In [74]:
df_cem2=pd.concat([df_cem1,df_cem.iloc[:,-1]],axis=1)

In [75]:
df_cem2

Comp1_cem  Comp2_Blast  Comp3_Ash  Comp4_water  Comp5_plasticizer  \
0      2.477918    -0.856886  -0.847132    -0.916663          -0.620225   
1      2.477918    -0.856886  -0.847132    -0.916663          -0.620225   
2      0.491443     0.795533  -0.847132     2.175367          -1.038944   
3      0.491443     0.795533  -0.847132     2.175367          -1.038944   
4     -0.790432     0.678414  -0.847132     0.488805          -1.038944   
...         ...          ...        ...          ...                ...   
1025  -0.045623     0.488241   0.564569    -0.092122           0.451695   
1026   0.392837    -0.856886   0.960095     0.676201           0.702927   
1027  -1.270057     0.759585   0.850661     0.521599          -0.017270   
1028  -1.168580     1.308072  -0.847132    -0.279518           0.853666   
1029  -0.194010     0.308504   0.376967     0.891706           0.401449   

      Comp6_Coarse  Comp7_Agg       Age        CCS  
0         0.863160  -1.217658 -0.279733  79.986111  
1         1.056170  -1.217658 -0.279733  61.887366  
2        -0.526514  -2.240913  3.553066  40.269535  
3        -0.526514  -2.240913  5.057677  41.052780  
4         0.070531   0.647908  4.978487  44.296075  
...            ...        ...       ...        ...  
1025     -1.323003  -0.065874 -0.279733  44.284354  
1026     -1.994679   0.496916 -0.279733  31.178794  
1027     -1.036061   0.080127 -0.279733  23.696601  
1028      0.214646   0.191188 -0.279733  32.768036  
1029     -1.395060  -0.150729 -0.279733  32.401235  

[1030 rows x 9 columns]

In [76]:
from sklearn.model_selection import train_test_split

x=df_cem2.iloc[:,:-1]
y=df_cem2.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.3)

In [77]:
y_test

339     21.911547
244     19.932751
882     36.438807
567     11.957582
923     39.844818
          ...    
1018    37.265488
1015    52.426376
341     47.401475
750     44.091990
937     36.804918
Name: CCS, Length: 309, dtype: float64

In [78]:
from sklearn.linear_model import LinearRegression
import sklearn.metrics


In [79]:
LR=LinearRegression()
LR.fit(x_train,y_train)
ypred=LR.predict(x_test)


In [80]:

print("MSE",sklearn.metrics.mean_squared_error(ypred,y_test))
print("Mean Absolute Error",sklearn.metrics.mean_absolute_error(y_test,ypred))
print("Root mean squared error",math.sqrt(sklearn.metrics.mean_squared_error(y_test,ypred)))
print("Rsquared",sklearn.metrics.r2_score(y_test,ypred))

MSE 120.19296189135137
Mean Absolute Error 8.712005247442644
Root mean squared error 10.963255077364176
Rsquared 0.5414363184391058


In [82]:
import statsmodels.api as sm
x_train=sm.add_constant(x_train)
lm_l=sm.OLS(y_train,x_train).fit()
print(lm_l.summary())


                            OLS Regression Results                            
Dep. Variable:                    CCS   R-squared:                       0.641
Model:                            OLS   Adj. R-squared:                  0.637
Method:                 Least Squares   F-statistic:                     159.0
Date:                Tue, 25 Jan 2022   Prob (F-statistic):          7.31e-153
Time:                        00:23:40   Log-Likelihood:                -2692.3
No. Observations:                 721   AIC:                             5403.
Df Residuals:                     712   BIC:                             5444.
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                36.0342      0.38